### ISSUE TITLE
Show Wikipedia, Pleiades, Google Maps links in places "See Also" section

### ISSUE THREAD

**Issue by tacarlson** [srophe/srp-places-app#10]
Re-use icons as well to teach users to recognize the icons.

**Comment by davidamichelson** [comment]
Would it help this if we added `<label>` in the TEI records so you could label these URLS?

**Comment by paregorios** [comment]
If you just want them to have a generic label associated with the resource (e.g., "Wikipedia" or "Pleiades"), then that's not necessary. But if you'd like something more specific (i.e., different for each place in each resource context) then that would be a reason to use label. 

Tom

Tom Elliott, Ph.D.
Associate Director for Digital Programs and Senior Research Scholar
Institute for the Study of the Ancient World (NYU)
http://isaw.nyu.edu/people/staff/tom-elliott

**Comment by davidamichelson** [comment]
The labels don't need to be item specific, just: "Comprehensive Bibliography on Syriac Christianity", "Pleiades", "Wikipedia", etc. Will you generate that based on identifying the domain name?

Also, here is our preferred listing order:
1. Comprehensive Bibliography on Syriac Christianity
2. Pleiades
3. Anything else (I am not sure there is at the moment)
4. Wikipedia

thanks!

**Comment by paregorios** [comment]
Yes, that's great.

Tom Elliott, Ph.D.
Associate Director for Digital Programs and Senior Research Scholar
Institute for the Study of the Ancient World (NYU)
http://isaw.nyu.edu/people/staff/tom-elliott

**Comment by davidamichelson** [comment]
@paregorios I've assigned this to Winona, just FYI.

**Comment by wsalesky** [comment]
@davidamichelson 
This is the only label I have a question about. Can you tell me which link is using this label: 
Comprehensive Bibliography on Syriac Christianity
