### ISSUE TITLE
Modify Nav Bar to take out "Home" link

### ISSUE THREAD

**Issue by tacarlson** [srophe/srp-places-app#110]
Instead, make "The Syriac Gazetteer" a link to the home page.  @davidamichelson : I think this exceeds my technical ability, at least without potentially clashing with someone.  Should this be assigned to @wsalesky or to @paregorios ?

**Comment by davidamichelson** [comment]
Yes please do assign it to Winona and if she cannot do it perhaps Tom can.

**Comment by wsalesky** [comment]
I can take care of it.
