### ISSUE TITLE
Make new content of static pages appear

### ISSUE THREAD

**Issue by tacarlson** [srophe/srp-places-app#111]
I replaced the lorem ipsum on the various pages, but the srp-places-app doesn't yet display the new prose.  Is there something I need to do make the static pages publicly visible?

**Comment by paregorios** [comment]
Has to be merged into the gh-pages branch from master. I can do it for you if you like.

Tom Elliott, Ph.D.
Associate Director for Digital Programs and Senior Research Scholar
Institute for the Study of the Ancient World (NYU)
http://isaw.nyu.edu/people/staff/tom-elliott

**Comment by wsalesky** [comment]
I can merge this tonight if you like, I have some changes I want to merge as well.

**Comment by tacarlson** [comment]
Great, thanks wsalesky!
