### ISSUE TITLE
Design touchup

### ISSUE THREAD

**Issue by wsalesky** [srophe/srp-places-app#113]
Re-organize data and structure of page for easier readability.

**Comment by wsalesky** [comment]
@davidamichelson @tacarlson 
I have done a little reworking of the page layout. I have two designs to push to the public pages, but want to make sure @tacarlson has already demoed the pages. Let me know when the coast is clear and I will push the changes to the gh-pages branch.

**Comment by tacarlson** [comment]
Demo is done.  Full speed ahead.

**Comment by wsalesky** [comment]
Okay. Here you go:
http://srophe.github.io/srp-places-app/exmple2.html

Just a starting point. I did not change the header as you had talked about a logo, that would effect color ect. in the header.
