### ISSUE TITLE
See also CBSC link broken

### ISSUE THREAD

**Issue by tacarlson** [srophe/srp-places-app#119]
Links to the Comprehensive Bibliography on Syriac Christianity under the See Also heading are broken.  It looks like there is white-space on either side of the link which causes the URL to be interpreted as relative instead of absolute.  Thanks!

**Comment by wsalesky** [comment]
I also noticed with 230.html there are two links to this resource, two different listings, would you like me to add the article title to the link, as we did for the wikipedia links?

**Comment by tacarlson** [comment]
That would be great!  The article title is what follows the "sK=" in the URL.  Thanks for thinking of this!
