### ISSUE TITLE
Add mapping mashup in places entry records

### ISSUE THREAD

**Issue by tacarlson** [srophe/srp-places-app#12]
Google maps to start with, perhaps review other options.

**Comment by sgillies** [comment]
As discussed on Skype just seconds ago, we'll use a MapBox terrain base map.

**Comment by paregorios** [comment]
this is blocked by #67

**Comment by paregorios** [comment]
unblocked and implementation merged at https://github.com/srophe/srp-places-app/commit/c284cfc43a64e730756f85219368af7867b31844
