### ISSUE TITLE
Add letter links to top of browse lists

### ISSUE THREAD

**Issue by tacarlson** [srophe/srp-places-app#121]
Because the browse list is long, it would be great if underneath the language tab on the browse page there could be first-letter links to the place in the list where places beginning with "B" start to occur (then "C", "D", etc.).  Similarly for browsing in Syriac, having links attached to the letters ܐ ܒ ܓ ܕ ܗ ܘ ܙ ܚ ܛ ܝ ܟ ܠ ܡ ܢ ܣ ܥ ܦ ܩ ܪ ܫ ܬ .

**Comment by wsalesky** [comment]
Done in eXist version.
