### ISSUE TITLE
Ignore a prefix "al-" in alphabetizing the browse list in English

### ISSUE THREAD

**Issue by tacarlson** [srophe/srp-places-app#122]
"al-" is the definite article in Arabic, and should be ignored for the alphabetization order in the browse list in English.  Then whatever letter follows "al-" should be treated as elsewhere in the list (e.g. an 'h' or 't' with a dot is alphabetized as if the 'h' or 't' did not have a dot, an initial ʿ is ignored, etc.).

**Comment by wsalesky** [comment]
Done in eXist version
