### ISSUE TITLE
Question about id in atom feed

### ISSUE THREAD

**Issue by wsalesky** [srophe/srp-places-app#123]
@davidamichelson @tacarlson @paregorios 
Currently an entry id looks like this:
tag:syriaca.org,2013:place-754

Should it instead be 
tag:syriaca.org,2013:754

The second seems more consistent with how we are identifying places via uris ect.

**Comment by paregorios** [comment]
My only concern with the latter approach is that then if you have a person whose uri is http://syriaca.org/person/754, what do you do?

Tom Elliott, Ph.D.
Associate Director for Digital Programs and Senior Research Scholar
Institute for the Study of the Ancient World (NYU)
http://isaw.nyu.edu/people/staff/tom-elliott

**Comment by wsalesky** [comment]
good point, I forgot about that pesky persons data that is just around the corner.
