### ISSUE TITLE
Browse tab labels "English" and "Syriac Gazetteer Number"

### ISSUE THREAD

**Issue by tacarlson** [srophe/srp-places-app#13]
My preference is to capitalize both, and note the missing 'e' needs to be added in "gazetter".

**Comment by tacarlson** [comment]
Still showing "english" and "syriac gazetter number" (instead of "gazetteer" with three e's) on the tabs of the re-loaded browse.

**Comment by paregorios** [comment]
try it now (you may need a refresh); I got slowed down pushing the changed code out to the web view

**Comment by tacarlson** [comment]
Now it works!  Thanks!
