### ISSUE TITLE
get rid of "by gazetteer number" listing on browse page

### ISSUE THREAD

**Issue by paregorios** [srophe/srp-places-app#15]
split out from #4 since we want to be able to time/implement this separately; we're presently deferring this pending OK from @tacarlson who is currently using the numeric listing for data debug

**Comment by wsalesky** [comment]
Just going through the list, do we want to keep the browse by number or no?

**Comment by tacarlson** [comment]
This should go away now.  It was useful for me earlier, but would only be misleading for users (because of the _almost_ alphabetical order).

**Comment by davidamichelson** [comment]
Agree. Though it would be useful perhaps to keep as an easter egg (e.g. don't include a link to it anywhere) but for advanced users we could still make it available.

**Comment by wsalesky** [comment]
Sounds good. To access it you would use this param: ?lang=num
