### ISSUE TITLE
start using structured bibl data instead of internal references

### ISSUE THREAD

**Issue by paregorios** [srophe/srp-places-app#18]

**Comment by tacarlson** [comment]
I'm thinking that we need proper footnotes before the initial demo, which means either pulling the full bibliographic information from structured bibl data or my adding additional markup to the <bibl> elements within each place, so that we can surface &lt;author>, &lt;title> (&lt;pubPlace>: &lt;publisher>, &lt;date>) in each footnote.

**Comment by davidamichelson** [comment]
I agree with this. Tom what do you prefer?

**Comment by paregorios** [comment]
I'd like to pull from the structured bibliographic data.

**Comment by davidamichelson** [comment]
Okay, I am note sure that we have drafted TEI documents to hold this yet.

**Comment by paregorios** [comment]
errr, is it not this: https://github.com/srophe/bibl ??

**Comment by tacarlson** [comment]
Yep, that's where our full bibl records are stored, and we have TEI for every bibl item cited in our TEI so far.

**Comment by paregorios** [comment]
I am now working on this issue in [branch18](https://github.com/srophe/srp-places-app/tree/issue18)

**Comment by davidamichelson** [comment]
Ha ha, sorry @tacarlson for misleading on this (great work on this Bibls). What I meant @paregorios in my comment was that you and I have not reviewed https://github.com/srophe/bibl to see if the TEI  there is what we want. Let's work with it for now, but next week we should vet it. And, I did write to ask for a copy of the endnote file, so hopefully we will have that soon.  Thanks to both of you for your work!

**Comment by tacarlson** [comment]
Early head's-up on additional issue: for places that have GEDSH articles (77 places) we need to cite the GEDSH article as well as GEDSH maps.  Between creating additional TEI files for each article and encoding article information in the spreadsheet and then in the place TEI, at least as a temporary measure, which do you think will work better?

**Comment by davidamichelson** [comment]
Each article will need its own BIBL URI eventually anyway. So its not lost
work to start the individual files now. You should be able to use a
template file since the entries will have alot of information that is the
same.

**Comment by paregorios** [comment]
so, could I propose that we use short-form citation in the sources list at the bottom of each page, with links back to the full references? So, e.g.: "GEDSH Map I A2, II A2" instead of Sebastian P. Brock et al. (eds.).The Gorgias Encyclopedic Dictionary of the Syriac Heritage. Piscataway, NJ. 2011. Map I A2, II A2." Thoughts?

**Comment by davidamichelson** [comment]
We did consider this but rejected it because users may not be familiar with it. Since it is at the bottom of the page, I would like to keep the full citation. Eventually there will be lots of references in here and many of them obscure, so we would be best keeping the data as clear as possible.

**Comment by paregorios** [comment]
ok

**Comment by paregorios** [comment]
Does this look like what you guys are after (click to expand)? 
![sourcegrab](https://f.cloud.github.com/assets/263285/844611/5fb1ef64-f3d6-11e2-81aa-60037c80ff3c.png)

**Comment by davidamichelson** [comment]
Great work!

----- Reply message -----

**Comment by paregorios** [comment]
had to go ahead and merge the branch cuz I made a git mess locally; apologies for subverting the workflow paradigm

**Comment by davidamichelson** [comment]
No harm done here.

**Comment by davidamichelson** [comment]
@tacarlson I just realized that we do not have Moosa or Dolabani in the bibls as translators, should we encode that and surface it, especially since we want people to know the Syriac was Dolabanis?

**Comment by tacarlson** [comment]
My bad!  I'll get that in tomorrow.

**Comment by davidamichelson** [comment]
No apology needed and sorry not to catch it until now. Alas @paregorios
that will be one more thing to surface in here. Do you think we can figure
out your XSL and do it ourselves?

**Comment by paregorios** [comment]
Well, I'm fiddling about with both the bibliography and citation stuff in the issue34 branch, so maybe leave this one to me?

Tom Elliott, Ph.D.
Associate Director for Digital Programs and Senior Research Scholar
Institute for the Study of the Ancient World (NYU)
http://isaw.nyu.edu/people/staff/tom-elliott

**Comment by davidamichelson** [comment]
Okay! (Though we should learn how to tweak your XSL eventually).

**Comment by tacarlson** [comment]
translator information is entered and the new files pushed to srophe\bibl

**Comment by davidamichelson** [comment]
Thanks!
