### ISSUE TITLE
Pick a more aesthetically pleasing Arabic font

### ISSUE THREAD

**Issue by tacarlson** [srophe/srp-places-app#25]
The main Arabic font used by Arabic Wikipedia would be a good choice, but I don't know how to find out what that is.

**Comment by paregorios** [comment]
unless they're doing something fancy in script or css I don't understand, it seems to be simply "arial, sans-serif", so either the arial font you have on your machine has very nice arabic or you don't have an arial with an arabic seciton and its picking up something else on your machine. want to paste some of their text into a word processor on your machine, force it to be "arial" and see if it looks the same to you?

**Comment by tacarlson** [comment]
Arial sans-serif sounds great.  It's what I normally use.
