### ISSUE TITLE
Subordinate Places: Labels

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srp-places-app#29]
Tom, let's also include the place type label in the list of subordinate places [e.g. ‘Amādīyā (region)] to avoid giving the illusion of missing data (for example the list for ‘Amādīyā (region) is only the districts [e.g. Dohuk (district)] but technically each of the settlements in the districts is also subordinate to the region.

Further thought, do we want to keep "subordinate" or do we want to say "contains", subordinate is more accurate while contains is more readily understandable.

Thomas C. please feel free to weigh in.

**Comment by tacarlson** [comment]
I like "Contains" as a relation heading, and including the type in parentheses to disambiguate.  But three cheers for pulling in linked data!

**Comment by davidamichelson** [comment]
Okay, two votes for contains then please Tom.

**Comment by paregorios** [comment]
I'm working on this in branch issue29
