### ISSUE TITLE
parentheses don't dislay correctly in browse by Syriac name

### ISSUE THREAD

**Issue by nathangibson** [srophe/srp-places-app#3]
See  ܐܘܚܕܢܐ ܕܨܘܪܐ — al-Ṣawr (province)

**Comment by paregorios** [comment]
Here's what I see on the current release (which probably has changed code from what you saw). This is what I expect, but then I'm not the target user. Should I be seeing something different, or did I 'accidentally' already fix the problem that you saw previously? 

![parens](https://f.cloud.github.com/assets/263285/785212/ca232f34-ea76-11e2-840c-eb76f654a679.png)

**Comment by nathangibson** [comment]
It's fixed now, both in your screenshot and when I browse to it. Thanks!

**Comment by paregorios** [comment]
closing
