### ISSUE TITLE
District/Region label confusion (not sure if this in the TEI record or the CSS)

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srp-places-app#30]
Should http://srophe.github.io/srp-places-app/places/742.html be a region or a district?

It is labeled region at http://srophe.github.io/srp-places-app/places/742.html

but district at http://srophe.github.io/srp-places-app/places/883.html

**Comment by tacarlson** [comment]
This is a vocabulary disagreement between Wilmshurst and TEI.  Wilmshurst distinguishes larger areas (regions) from smaller areas (districts), while TEI <district> element refers to a portion of a city.  Since Wilmshurst (almost always) only has two levels of containing areas of land, his classification works for him, but Syriaca.org may have multiple levels of territories containing territories, so I have made all areas of territory of type "region" whether large or small.  To avoid confusion, the Syriaca.org type for a portion of a city is "quarter" rather than "district."

**Comment by davidamichelson** [comment]
Okay, I see that now, but the labelling is still confusing since in one
place in the app we are calling it a district and in another a region.
Could we indicate the level relationship some how while still labeling both
as regions.

 Abnāye (settlement) is located in Gwerkel (region) and Gāzartā (region).

**Comment by tacarlson** [comment]
We might even do "Abnāye (settlement) is located in Gwerkel (region) within Gāzartā (region)."  I was attempting to reproduce as exactly as reasonably possible the format of Wilmshurst's index entry, but we are not obligated to do so.

For a location, would we want a full sentence like that above?  Or perhaps a more abbreviated "Contained by Gwerkel (region) within Gāzartā (region)"?

**Comment by davidamichelson** [comment]
"within" is perfect. I think the shorter prose is better unless you feel
the other is needed for clarity.

Also let's ask Tom Elliot does he want you and I to edit the XSL/CSS for
these type of things?

**Comment by paregorios** [comment]
Apropos the last question, see the email I just sent RE workflow. If you're immediately hot to work on a particular thing, by all means open a branch locally with a name like "issue30" and push it back to github. You might also care to add a comment to the associated issue saying you've created a corresponding working branch or something. Let me know if any of this doesn't make sense?

**Comment by paregorios** [comment]
so, I'm thinking that issue #24, once addressed, will take care of this. Am I right?

**Comment by tacarlson** [comment]
I think so.  The only remaining element in this issue is the discussion in the notes to make children of a <location type="nested"> appear in document order with "within" appearing before each one (ideally capitalized in the first instance).  I repeated that in the comments for #24 as well.

**Comment by paregorios** [comment]
thanks @tacarlson ... understood

**Comment by paregorios** [comment]
I'm working on this in branch "issue30"
