### ISSUE TITLE
Labeling unsourced Syriaca Headwords

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srp-places-app#31]
When we do not have a source for the Syriaca headwords no footnote is shown: see http://srophe.github.io/srp-places-app/places/658.html

This may be confusing for some users who will wonder where the names came from. We do explain this in the TEI header (editorialDecl) but perhaps this needs to be surfaced. I might be inclined to just publish it with a footnote, that explains no source.

**Comment by tacarlson** [comment]
Are you thinking surfacing the <catDesc> of the <category xml:id="syriaca-headword">?  It's a bit longer than other footnotes.  Perhaps just the tail end of that: "This name has been created according to the Syriac.org guidelines for headwords: <a href="http://syriaca.org/documentation/headwords.html">http://syriaca.org/documentation/headwords.html</href>." ?

**Comment by davidamichelson** [comment]
That would be fine.

**Comment by davidamichelson** [comment]
@tacarlson @paregorios Perhaps we should make the unsourced headwords conform to our source style and add http://syriaca.org/documentation/headwords.html as their source in the TEI. I would still like to have the note include, however, "This name has been created according to the Syriac.org guidelines for headwords" so users see immediately that it is not on par with the others. We could add a note to the bibl entry...

**Comment by paregorios** [comment]
So, if everyone's +1 on adding this encoding to the source data, please someone open an appropriate ticket on the places repos and cross-reference it from here ... there are (as of a few minutes ago) a couple of examples where I've done this.

**Comment by paregorios** [comment]
also, please confirm whether this enhancement is needed for the pre-demo milestone :)

**Comment by tacarlson** [comment]
I have some concerns about whether and how to do this.  Perhaps we can discuss on Wednesday?

**Comment by paregorios** [comment]
OK: I'll tag for discussion Wednesday

**Comment by davidamichelson** [comment]
We will solve by adding a line to the page
 Information without attribution has been created following the Syriac.org <a href="http://syriaca.org/documentation/">guidelines</a>.

**Comment by tacarlson** [comment]
This is a `<test>`.

**Comment by davidamichelson** [comment]
@paregorios Okay, I have inserted the change and synced the branch with github. Can you look at it and then merge please? (Note the branch list does not show my update for some reason, but you can see it here: https://github.com/srophe/srp-places-app/compare/master...Issue31)

Also, I used `<small>` in the html is that allowed or should I have stuck with `<p>`?

**Comment by paregorios** [comment]
@davidamichelson I can see the link, but there's something else weird going on, which I won't be able to look into until tomorrow. Let's put off doing another one of these until I can asses. Thanks.

**Comment by davidamichelson** [comment]
Hi Tom, it looks like you merged this? Shall we close the issue out? Was there a problem with the way my github client created the branch?

**Comment by paregorios** [comment]
This did get merged, so I'm closing the issue; but there was still something weird about the process so we'll need to walk through another case before we're confident about the behaviors of the GUI client.
