### ISSUE TITLE
Add citation and attribution/copyright information to each page

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srp-places-app#34]

**Comment by paregorios** [comment]
as soon as @davidamichelson or another member of his team can provide a sketch of what's wanted, we'll implement.

**Comment by davidamichelson** [comment]
Here is a mock up, but we need to have a bit of an extended conversation, so see this google doc where I have pasted in TEI elements etc: https://docs.google.com/document/d/1LiVrzCKqSjYsYrBb8KKFdPVITZBP6kyKeztxCcAzsrw/edit?usp=sharing

# How to Cite This Entry:

### Note:

T. Carlson, "Edessa/ܐܘܪܗܝ" in _The Syriac Gazetteer_, eds. D. Michelson and T. Carlson, entry published July 10, 2013, Syriaca.org: The Syriac Reference Portal, ed. D. Michelson, http://syriaca.org/place/78/source

### Bibliography:

Carlson, T. "Edessa/ܐܘܪܗܝ." In _The Syriac Gazetteer_, edited by D. Michelson and T. Carlson. Entry published July 10, 2013. Syriaca.org: The Syriac Reference Portal, edited by D. Michelson. http://syriaca.org/place/78/source

# About this Entry:

**Entry Title:** Edessa/ܐܘܪܗܝ
**Entry Contributor:** Thomas A. Carlson
**Publication Date:** July 10, 2013
**URI:** http://syriaca.org/place/78/source

#### Authorial and Editorial Responsibility:
- David A. Michelson, general editor, Syriaca.org: The Syriac Reference Portal
- David A. Michelson and Thomas A. Carlson, editors, _The Syriac Gazetteer_
- Thomas A. Carlson, entry contributor, "Edessa/ܐܘܪܗܝ"

#### Additional Credit:
- Initial Barsoum entry creation by David A. Michelson
- Data merging, Pleiades and Wikipedia linking, and XML by Thomas A. Carlson
- Syriac description entry by Robert Aydin
- Arabic description entry by Dayroyo Roger-Youssef Akhrass
- Wilmshurst index information entry by Anthony Davis

**Comment by paregorios** [comment]
so, when do you want to have this conversation?

**Comment by davidamichelson** [comment]
Well actually we can do it online here, are any of the items I list important or can we fix them later?

There are a couple of current processing questions for you to consider:
- we are relying on <titleStmt><principal> for the General Editor which does not have an xml id. Perhaps we should add this in for some future date when I am dead and not the principal? Or add a role type in <editor> for that.
- Also, the <publicationStmt><authority>Syriaca.org: The Syriac Reference Portal</authority> does not have an XML id, we might want to add that for when we get records from other projects?
- the file http://syriaca.org/editors.xml does not have an abbreviated first initial,  should we add this to keep our citations short?
- We have a choice on dates. It seems easier to use a publication date rather than an access date since then we would have to also indicate the edition number, but it does give less information.
- Do we use the URI for the XML file? Chicago style prefers DOIs to URLs, so I think would also prefer URI's, but users want a resolvable link to something they can read (thus not the XML, so kind of they really want the URI for the place not the place file). Also technically, do we want to create Bibl URIs for each XML documents? ;) That is an infinite loop of sorts.
  It also occurs to me know that we probably need a publication statement actually in the record itself too.

**Comment by tacarlson** [comment]
Just a note that TEI elements do not appear in GitHub comments unless the less-than character &lt; is escaped out using an ampersand, so I cannot see the TEI elements in the earlier comments.

**Comment by davidamichelson** [comment]
They are only in the google doc since I discovered that as well. They are a rough and messy mock up anyway. What do you think of my draft?

----- Reply message -----

**Comment by paregorios** [comment]
this is in progress in branch issue34

**Comment by davidamichelson** [comment]
One more note to discuss tomorrow. We probably need to include in the TEI a way to generate an attribution for places where we are incorporating cc-by data into our data so that users have one nice and tidy license statement if they want to reproduce the whole record. This could go in the Bibl, but needs to be surfaced in our CC-By statement.

For example:

# Copyright and License for Reuse

Except otherwise noted, this page is © DATE `<pull from publication date in TEI>` Syriaca.org and is licensed for reuse under a Creative Commons Attribution license: http://creativecommons.org/licenses/by/3.0/.

This entry incorporates copyrighted material from the following work(s):
- I.A. Barsoum, The Scattered Pearls, © 1991 Bar Hebraeus Verlag (used under a Creative Commons Attribution license: http://creativecommons.org/licenses/by/3.0/).

## 

Also, there is great RDFa data for CC attribution we should include since we love linked data so much :) see http://wiki.creativecommons.org/Marking_works

**Comment by paregorios** [comment]
per discussion the other day, we're going to move this content down the page into the footer

**Comment by paregorios** [comment]
seems like we made a decision(?) in conversation the other day about retitling "URI" in this listing and what it should actually be... but we don't seem to have captured that decision here in the ticket ... help?

**Comment by davidamichelson** [comment]
The URI line in about this page gets deleted. The url at the end of the citation should be .html rather source

----- Reply message -----

**Comment by paregorios** [comment]
@davidamichelson REI the URI and URL: understood; thanks.

**Comment by paregorios** [comment]
this is bascially done, and I'm shortly going to push and merge the branch. Since it's such a huge lot of functionality, I'd rather go ahead and merge and close this ticket. It won't disappear, but since it's already looking like a big string of sausages, I think it would be better if we opened new, more atomic issues to address any bugs we spot or enhancements we think up.

**Comment by paregorios** [comment]
new versions have been published to the web test site

**Comment by davidamichelson** [comment]
@paregorios Looks great! Great work. I'll be out of email range til monday.
