### ISSUE TITLE
change browse page logic: list all

### ISSUE THREAD

**Issue by paregorios** [srophe/srp-places-app#4]
list all places in every entry, even if no placename available in that language

**Comment by paregorios** [comment]
get rid of "by number" tab

**Comment by tacarlson** [comment]
Please hold off on this until we stop using the spreadsheet, because the "by number" tab is very useful for comparing the browse with the spreadsheet.

**Comment by paregorios** [comment]
split out the "by number" listing issue to ticket #15 so we can move forward on the issue of completeness with this ticket
