### ISSUE TITLE
Add CBSC entry names to citation, with links to CBSC

### ISSUE THREAD

**Issue by tacarlson** [srophe/srp-places-app#42]
In the new data which I just committed, within the &lt;bibl> entries pointing to the Comprehensive Bibliography on Syriac Christianity (CBSC) I have added a &lt;title> with @level="a" whose content is the names of the CBSC entry or entries for this place (within quotes, comma-separated).  Within the &lt;bibl> I also added &lt;ref> element(s) whose @target attribute(s) point(s) to the CBSC entry URLs (which are not URIs, and have nasty ampersands and spaces, so ampersands are encoded with &amp;amp;).

It would be great if we could surface the article titles and make each article title a link to the CBSC entry corresponding to it.  Each CBSC link should contain the article title exactly, and I do not believe there are any truncation collisions (e.g. where one of the names of this place is a proper substring of another).  So if you iterate through the article titles (stripping out quotation marks and comma) you can search which &lt;ref> has a @target which contains that string.

This is of course a temporary enhancement until we merge with CBSC, but Dave thought it would be worthwhile to enable this and then tweak it later.

**Comment by paregorios** [comment]
This approach has been changed to adding a citedRange element with attributes of unit=entry and target containing the url.

**Comment by paregorios** [comment]
initial demo milestone or defer?

**Comment by tacarlson** [comment]
I would put this in the initial demo, to show even our first users that there will be bibliographic information from CBSC where available (and to build good will with Sergey), even though the precise state of that info will change.  But it's @davidamichelson 's call.

**Comment by davidamichelson** [comment]
@paregorios We need a live link to CBSC in the demo either in the citation or in the see also section please. This will help in making the case to our biblio partners as Thomas notes and will give a fake taste of linked open data to our users since CBSC is a source they already use.
