### ISSUE TITLE
surface translators

### ISSUE THREAD

**Issue by paregorios** [srophe/srp-places-app#50]
when translators are indicated in source bibliography, serialize these into footnote and bibliographic citations

**Comment by paregorios** [comment]
is this a must-have for initial demo?

**Comment by davidamichelson** [comment]
Yes please put in initial demo. Given the specific nature of our data, translator is as essential as author.

**Comment by paregorios** [comment]
wilco

**Comment by davidamichelson** [comment]
These were showing up as eds in a previous push, but now they are gone.
