### ISSUE TITLE
Add placeholder text for null fields (eg missing Syriac name)

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srp-places-app#6]
Example: When no Syriac, then the HTML should insert "[Not Available]"

**Comment by paregorios** [comment]
This is on the browse page listings, right?

**Comment by davidamichelson** [comment]
I would put it on both the browse pages and the document page itself

**Comment by paregorios** [comment]
ok, thanks

**Comment by davidamichelson** [comment]
Okay, this one needs revision due to poor wording on my part. Seeing [Not Available] in the browse list makes it look like that entry is not available, not that there is no Syriac available. I will try to edit the CSS myself and see if I can find something that works better. How about [Syriac Not Available]? Or is this used for null fields in the English as well (there shouldn't be any I think).
