### ISSUE TITLE
Need GeoJSON views of places

### ISSUE THREAD

**Issue by sgillies** [srophe/srp-places-app#67]
Our maps will operate on GeoJSON views of places (maybe even people?). The mapping javascript in an HTML page like places/42 will look for a link with a GeoJSON data uri (see http://sgillies.net/blog/958/geojson-data-uris/). For example:

  <link rel="where" href="data:application/json,%7B%22type%22%3A%20%22Point%22%2C%20%22coordinates%22%3A%20%5B0.0%2C%200.0%5D%7D"/>

This saves us from an extra XSLT run and extra request per place. We probably still want to have a GeoJSON file for all places.

**Comment by paregorios** [comment]
this is a blocker for #12

**Comment by paregorios** [comment]
this is now implemented in [branch issue67](https://github.com/srophe/srp-places-app/tree/issue67). @sgillies please have a look and let me know if the json data URIs now appearing in the head sections of each of the HTML files do what you need. If so, we can go ahead and merge this branch and close the associated issue.

**Comment by paregorios** [comment]
fixed with https://github.com/srophe/srp-places-app/commit/c284cfc43a64e730756f85219368af7867b31844

**Comment by sgillies** [comment]
Found a problem. The coordinates property appears in HTML files as [, LONG LAT]. Should be [LONG, LAT].

**Comment by davidamichelson** [comment]
How does it appear in the TEI for each place? Do we we have it backward
there? It may just be in the order we got it from UNC.

**Comment by paregorios** [comment]
this is an xslt error in generating the json

Sent from my tricorder

Tom Elliott, Ph.D.
Associate Director for Digital Programs
Senior Research Scholar
Institute for the Study of the Ancient World
New York University
http://isaw.nyu.edu/people/staff/tom_elliott

**Comment by paregorios** [comment]
I'm working on fixing this now
