### ISSUE TITLE
Duplicate dc.title meta

### ISSUE THREAD

**Issue by sgillies** [srophe/srp-places-app#68]
See view-source:http://srophe.github.io/srp-places-app/places/5.html.

```
  <meta name="DC.title" property="dc.title" lang="en" content="Adharbayjān (region) — ܐܕܪܒܝܓܐܢ"></meta>
  <meta name="DC.title" property="dc.title" lang="en" content="The Syriac Gazetteer"></meta>
```

**Comment by davidamichelson** [comment]
That second one should be a higher level volume title and the first is the
article level.

**Comment by paregorios** [comment]
yeah, but they can't both be expressed as dc.title, so I need to investiage what to do.

**Comment by paregorios** [comment]
fixing this along with #67
