### ISSUE TITLE
Need to implement additional GRASS based geography module

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srp-places-app#77]
See: http://www.youtube.com/watch?v=U3Hf0qI4JLc#at=626 Probably for Sean to look into, has good Star Trek type features including voice over for GIS

**Comment by paregorios** [comment]
you, @davidamichelson, are a sick puppy ;)

**Comment by davidamichelson** [comment]
Okay, I would be willing to settle for having William Shatner do the voiceover for Syriaca.org at least. Can you guys arrange it?
