### ISSUE TITLE
Atom feed showing titles as "Null".

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srp-places-app#84]

**Comment by davidamichelson** [comment]
Tom, this does not have to be done for the initial demo unless you have a reason it should. Assign it where you think best.

**Comment by paregorios** [comment]
brief inspection indicates tags from the html namespace are getting into the atom title (e.g., bdi), which is what's causing the Firefox parser to barf on them, producing the "null" display. Need to change the way the title routines are called for Atom generation to get clean text.
