### ISSUE TITLE
Display name and confession attestations where we have them

### ISSUE THREAD

**Issue by tacarlson** [srophe/srp-places-app#90]
Places will have `<event>` elements of @type = "attestation" which are linked to the `<placeName>` or `<state type="confession">` elements by means of `<link>` elements.  We need to discuss how to display these, and we need to get some examples.

**Comment by tacarlson** [comment]
E.g. of name attestation: Edessa (78.xml, line 156-158 and 174)
https://github.com/srophe/places/blob/master/xml/78.xml#L156

E.g. of confession attestation: Edessa (78.xml, line 159-161 and 175)
https://github.com/srophe/places/blob/master/xml/78.xml#L159

**Comment by wsalesky** [comment]
Can I have an example of how you would like the output? Thanks!

**Comment by tacarlson** [comment]
I think it would be really cool to have mouse-over pop-up boxes which list the attestations for this particular name or confession, so that when the user hovers over the name or confession label, they see something like:

**Attestations of name ܐܘܪܗܝ:**
- 365: Ephrem, _Hymns Against Heretics_, 205 [footnote]
- <708: Yaʿqub of Edessa, _Letters_, 32 [footnote]
- >1146, <1234: _Chronicle of 1234_ [footnote]

**WARNING: the above attestations are fictional**

In order to do this, I'm realizing we'll need to put some additional structure into attestation events, and we need to figure out how to represent notBefore and notAfter attributes.

As an initial visualization, before adding structure to the attestation events, you could have a list:

**Attestations:**:
- 1146: Attestation of confession Syrian Orthodox in the anonymous Chronicle of 1234. [footnote]
- >1146, <1234: Attestation of name ܐܘܪܗܝ in the anonymous Chronicle of 1234. [footnote]

I would put this list above Sources and Errata, but below location, description, related events, people, etc.

BTW, I'm having trouble seeing the html with the modifications you've made.  http://srophe.github.io/srp-places-app/places/78.html appears without any related events, people or errata sections on my browser.  Am I doing something wrong?  I'm really looking forward to seeing the updated version!

**Comment by davidamichelson** [comment]
Thanks all, just to weigh in, I like the mouse over, but let's keep it
simple for now as a list. This will help us keep the page relatively
printable and viewable on mobile without extra styling.

**Comment by wsalesky** [comment]
Okay, we will keep it simple for now. 

Sorry, I forgot to push the changes to the gh-pages branch. You should be able to see the changes now.
