### ISSUE TITLE
Display errata notes and name deprecations

### ISSUE THREAD

**Issue by tacarlson** [srophe/srp-places-app#91]
Some entries have `<note type="errata">` elements (for example, 43.xml), while others have `<note type="deprecation">` elements which are linked to particular names to be deprecated by means of `<link>` elements (e.g. 518.xml).  Notes of both kinds should be displayed in an Errata section near the foot of the page.  Names which are linked to deprecation notes should not be displayed in the Name section at the top of the page, but should be displayed in the Errata section.

**Comment by tacarlson** [comment]
E.g. of errata note: Edessa (78.xml, line 172)
https://github.com/srophe/places/blob/master/xml/78.xml#L172

E.g. of name deprecation: Circesium (62.xml, line 138)
https://github.com/srophe/places/blob/master/xml/62.xml#L138

**Comment by wsalesky** [comment]
How far at the bottom of the page? Before the "how to cite this entry" under "about this entry?"

**Comment by tacarlson** [comment]
I would put it just above sources, but @davidamichelson might prefer just below sources.  I think of the "How to cite this entry" and everything below the line break as not part of the content itself, but metacontent.

**Comment by wsalesky** [comment]
I will put it below sources for now, it can easily be moved.

**Comment by wsalesky** [comment]
Sorry I meant just above sources.

**Comment by wsalesky** [comment]
Okay, this has been added. The names are currently just listed inline after the note (with footnotes). Please let me know if you would like this display changed, ie a list or something else.

**Comment by wsalesky** [comment]
Move name to front of note. Add colon between name and note. example: Syriac (fn): Note
