### ISSUE TITLE
Display events

### ISSUE THREAD

**Issue by tacarlson** [srophe/srp-places-app#92]
78.xml has `<event>` elements (whose type is not "attestation") which should be displayed in an "Events" section in the meat of the page.

**Comment by tacarlson** [comment]
Example: Edessa (78.xml, line 150-155)
https://github.com/srophe/places/blob/master/xml/78.xml#L150

**Comment by wsalesky** [comment]
strip 0 from dates
http://preview.github.io/?https://github.com/srophe/syriaca/blob/master/dates.html
