### ISSUE TITLE
Display related places

### ISSUE THREAD

**Issue by tacarlson** [srophe/srp-places-app#93]
78.xml has `<relation>` elements within the `<listplace>` element after the `<place>` element which point to related places along with their relationships.  We should have a "Related Places" section in the meat of the page which displays these.

**Comment by tacarlson** [comment]
Example: Edessa (78.xml, line 232)
https://github.com/srophe/places/blob/master/xml/78.xml#L232

**Comment by wsalesky** [comment]
@tacarlson @davidamichelson 
Any particular syntax you would prefer for displaying these relationships? 
The example in 78.xml could read as:
Edessa, in Osrhoene, in Roman Empire. -0363 (footnote)
Ephrem resided in Edessa. 0363-0373 (footnote)

These could also include information such as place type, such as Edessa, in the province of Osrhoene, or other data from the referenced files.
Thanks,
Winona

**Comment by davidamichelson** [comment]
I'll defer to Thomas, but we are also happy to edit the html if you can get the info in place in general.

----- Reply message -----

**Comment by tacarlson** [comment]
Since not all place relations will have date information, I think I would incline toward something like:
- Osrhoene contains Edessa (to 363) [footnote]
- Roman Empire contains Edessa (to 363) [footnote]
- Ephrem resided in Edessa (363-373) [footnote]

I split out the two "active" members of the former relation to create two separate bullet points from that, and then the latter relation in the code only leads to one sentence.

Would it be possible to strip leading zeros from the number?  The TEI requires four-digit years, but readers won't like them.

If there is no inception date, I would prefer "to 363" instead of "-363" to avoid the confusion of negative numbers (which we have in a few places, although I suppose they should be converted to BC or BCE [which to use is @davidamichelson 's call]).  For parallelism it might be nice to have "from 363" instead of "363-".

And, of course, it would be really cool if the references to other entities could be converted into links to those entities. =-)

I think inlining place types would be hard to make sound idiomatic in all cases (e.g. Edessa is on the river of Skirtos...), especially since sometimes our type sometimes does not match the case-specific usage (e.g. Piscataway, in the province of New Jersey, in the state of United States of America).  So I'd just stick with the place name, and if people want to know what it is, they can click through.

**Comment by wsalesky** [comment]
@tacarlson - that looks great. I will include links to the referenced entities.

**Comment by wsalesky** [comment]
I have added the related people and places. The only note I would like to make is that the links are pointing to pages that do not currently exist. I pointed to the urls in the related element assuming this will be the permanent url. This can be changed to be a relative url so you can use them, but there are no people html pages yet, so some will not work anyway.  

Changes to display, position ect. are easy to make so let me know if you would like something different.

**Comment by wsalesky** [comment]
remove spaces between ( and dates. 
make links relative.
