### ISSUE TITLE
Add footnote for quoted abstracts

### ISSUE THREAD

**Issue by tacarlson** [srophe/srp-places-app#94]
For some places the abstract (a `<desc>` whose xml:id contains "abstract") is derived from the GEDSH article (and thus the prose within the `<desc>` is wrapped in a `<quote>` whose source attribute points to the `<bibl>` corresponding to the GEDSH article).  These abstracts need a footnote indicating where these words came from.

**Comment by tacarlson** [comment]
E.g. 8.xml and 90.xml

**Comment by tacarlson** [comment]
DAM and I discussed this, and we're worried that our editorial board will see their words uncited.  So abstracts in `<quote>` elements should be wrapped in quotation marks and have a footnote.  Is that feasible for the first demo?

**Comment by davidamichelson** [comment]
@paregorios, sorry for the addition but we assume that this will just be
cutting and pasting some XSL we already have right?
